---
spring:
  profiles:
    active: local
---
spring:
  profiles: local
billing:
  datasource:
    host: 127.0.0.1
    port: 3306
    driver-class-name: com.mysql.jdbc.Driver
    username: sa_user
    password: usersa
    database: company
    maximum-pool-size: 50
